### PR TITLE
[WIP] Trial move on making it compiled with kf6 libs

### PR DESCRIPTION
**Pull request by Brli**
I tried a bit and copy/paste from multiple kde source to merge away from krun.

it currently has major unfunctional part:

the file chooser dialog pops only once, rather it's a upload or a download request, and never pops again, even triggering the same request, ie. click to save the same pic or click the same "click to upload" element.

the system:

```
OS: Arch
Firefox: 123.0.1
GUI Session: Plasma6 Wayland
Firefox: wayland
```

### CODE REVIEW

**Comment by Brli** [comment]
the best approach would be to pass things to xdg-portal and let it handle all these requests.

**Comment by Vogtinator** [comment]
> the best approach would be to pass things to xdg-portal and let it handle all these requests.

Yes, that's also my plan

**Comment by Brli** [comment]
firefox keeps reporting this to terminal, don't know if relevant.

```
(firefox:440032): Gdk-CRITICAL **: 14:53:56.118: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed
[Parent 440032, Main Thread] WARNING: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed: 'glib warning', file /build/firefox/src/firefox-123.0.1/toolkit/xre/nsSigHandlers.cpp:187
```

strace suggests that (yes, trying a nightly build from `mozilla-central` mercurial source with kde patches and co.)

```
write(2, "[Parent 451743, Main Thread] WAR"..., 128[Parent 451743, Main Thread] WARNING: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed: 'glib warning', fil) = 128
write(2, "e /build/firefox-nightly-brli/sr"..., 84e /build/firefox-nightly/src/mozilla-central/toolkit/xre/nsSigHandlers.cpp:187
) = 84
ioctl(2, TCGETS, 0x7ffd85ca5250)        = -1 ENOTTY (Inappropriate ioctl for device)
getpid()                                = 451743
write(2, "\n(firefox:451743): Gdk-CRITICAL "..., 120
(firefox:451743): Gdk-CRITICAL **: 15:10:51.418: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed
) = 120
write(67, "GETOPENFILENAME\n/home/brli/Deskt"..., 221) = -1 EPIPE (Broken pipe)
--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=451743, si_uid=1000} ---
```

**Comment by Brli** [comment]
it seems somehow `Helper::handleGetOpenOrSaveX()` is written purely in Qt, instead of Kf5 libs.

**Pull request closed without merging**
