### PR TITLE
Improve HiDPI suport

### PR DESCRIPTION
**Pull request by equeim**

### CODE REVIEW

**Comment by Vogtinator** [comment]
Thanks!

Can you also enable `AA_EnableHighDpiScaling`? In a Plasma session this is usually hard-disabled by environment variables, but it's more complete that way.

**Comment by equeim** [comment]
Which env variable disables it? For Plasma only sets QT_SCREEN_SCALE_FACTORS and programs are scaled properly. Also AFAIK no KDE app sets this attribute manually.

**Comment by Vogtinator** [comment]
> Which env variable disables it?

`QT_AUTO_SCREEN_SCALE_FACTOR=0`

> Also AFAIK no KDE app sets this attribute manually.

Those which are used outside of Plasma do.

**Comment by equeim** [comment]
Ah, I thought that automatic scaling is enabled by default. What is minimum version of Qt for kmozillahelper? Qt::AA_EnableHighDpiScaling was introduced in 5.6.

**Comment by Vogtinator** [comment]
The oldest Qt kmozillahelper is build with is from Leap 42.3, which ships 5.6.2.

**Pull request merged**
